# Generated by Django 3.1.5 on 2021-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('proteins', models.DecimalField(decimal_places=1, help_text='Amount of proteins in 100g of a product', max_digits=3)),
                ('fats', models.DecimalField(decimal_places=1, help_text='Amount of fats in 100g of a product', max_digits=3)),
                ('carbohydrates', models.DecimalField(decimal_places=1, help_text='Amount of carbohydrates in 100g of a product', max_digits=3)),
                ('composition', models.TextField(help_text='What this product contains')),
                ('price', models.DecimalField(decimal_places=2, help_text='price in $', max_digits=5)),
            ],
        ),
    ]
