# Generated by Django 3.1.5 on 2021-01-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_menu_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Pizza',
        ),
    ]
