# Generated by Django 3.1.5 on 2021-01-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_auto_20210113_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=15.14, help_text='Amount of calories in 100g of a product', max_digits=3),
            preserve_default=False,
        ),
    ]
