# Generated by Django 3.1.5 on 2021-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_pizza_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='calories',
            field=models.DecimalField(decimal_places=1, help_text='Amount of calories in 100g of a product', max_digits=5),
        ),
    ]
