# Generated by Django 3.1.5 on 2021-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_auto_20210115_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='calories',
            field=models.DecimalField(decimal_places=0, help_text='Amount of calories in 100g of a product', max_digits=3),
        ),
    ]
