# Generated by Django 3.1.5 on 2021-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_auto_20210115_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.CharField(choices=[('YES', 'Smoking table'), ('NO', 'No smoking table')], help_text='Is smoking allowed?', max_length=4)),
                ('location', models.CharField(choices=[('WND', 'Near to window'), ('CEN', 'In center of restaurant'), ('COR', 'Corner of restaurant')], help_text='Where is the table?', max_length=3)),
                ('capacity', models.IntegerField(help_text='How much persons can be placed here?')),
            ],
        ),
    ]
