# Generated by Django 3.1.5 on 2021-01-22 15:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=32)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone', max_length=128, region=None)),
                ('date', models.DateField(auto_now=True, help_text='Day of the order')),
                ('time_from', models.TimeField(auto_now=True, help_text='Reservation start')),
                ('time_to', models.TimeField(auto_now=True, help_text='Reservation end')),
                ('status', models.CharField(choices=[('SUBM', 'Submitted order'), ('CONF', 'Confirmed order'), ('CANC', 'Cancelled order')], default='SUBM', max_length=4)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.table')),
            ],
        ),
    ]
