# Generated by Django 3.1.5 on 2021-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=1, help_text='For how much persons?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='Day of the order'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.TimeField(help_text='Reservation start'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(help_text='Reservation end'),
        ),
    ]
