# Generated by Django 3.1.5 on 2021-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_auto_20210122_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.CharField(choices=[('WND', 'Near to window'), ('CEN', 'In the center of restaurant'), ('COR', 'Corner of restaurant')], help_text='Where is the table?', max_length=3),
        ),
    ]
